doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        
        # Ajoutez cette configuration pour gérer les ENUM
        types:
            enum: Doctrine\DBAL\Types\StringType
        mapping_types:
            enum: string
        
        # Décommentez et spécifiez votre version de MariaDB/MySQL
        server_version: 'mariadb-10.4.3'  # Adaptez à votre version
        
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system